@baseURL=http://localhost:4004/transactions
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiR3VpbGhlcm1lIiwiZW1haWwiOiJhQGEuY29tIiwic3Vic2NyaWJlciI6ZmFsc2UsImRlbGV0ZWRfYXQiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIwLTA1LTIyVDAzOjM0OjUyLjAwMDAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMC0wNS0yMlQwMzozNDo1Mi4wMDAwMDBaIn0sImlhdCI6MTU5MDI0ODQ3MiwiZXhwIjoxNTkwNjA4NDcyfQ.xuHBA9MQY0frsLqsq20UyGr_EVkADUFTE08YlpAPAOk

# Cria uma transação de entrada, feita para recarregar o saldo
POST {{baseURL}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "coins": 100,
    "type": "in"
}

# Cria uma transação de saída, feita para utilizar os créditos
POST {{baseURL}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "comment_id": 1,
    "coins": 10,
    "type": "out"
}

# Retorna o saldo do usuário já descontando as taxas do sistema
POST {{baseURL}}/balance
Authorization: Bearer {{token}}
Accept: application/json

# Confirma uma transação
POST {{baseURL}}/confirm/6
Authorization: Bearer {{token}}
Accept: application/json