<?php
return [
    /*
    |--------------------------------------------------------------------------
    | jwtExpireAfter
    |--------------------------------------------------------------------------
    |
    | Time to expire a JWT Token generated by login (in minutes)
    |
    */
    'expireAfter' => env('JWT_EXP', 10),

    'key' => env('JWT_KEY')
];