#!/bin/bash
cd ../services/gateway
./vendor/bin/openapi  --output ./public/swagger \
    ./app/Http/Controllers \
    ../users/app/Http/Controllers \
    ../comments/app/Http/Controllers \
    ../transactions/app/Http/Controllers \
    ../notifications/app/Http/Controllers