version: "3.5"

services:
    mysql_challenge:
        image: mysql:8.0
        container_name: challenge.mysql
        volumes:
            - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
            - ./data:/var/lib/mysql/
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234