@baseURL=http://localhost:4001

# Cria um usuário
POST {{baseURL}}/user
Content-Type: application/json
Accept: application/json

{
    "name": "Guilherme",
    "email": "a@a.com",
    "password": "123",
    "subscriber": false
}

@userID=1
# Retorna os dados de um usuário
GET {{baseURL}}/user/{{userID}}
Accept: application/json

@userID=1
# Atualiza um usuário
PUT {{baseURL}}/user/{{userID}}
Content-Type: application/json
Accept: application/json

{
    "subscriber": true
}

# Deleta um usuário
@userID=2
DELETE {{baseURL}}/user/{{userID}}
Accept: application/json

# Loga um usuário no sistema
POST {{baseURL}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "a@a.com",
    "password": "123"
}

# Verifica se um usuário é assinante
@userID=2
POST {{baseURL}}/is/subscriber/{{userID}}
Accept: application/json
